### ISSUE TITLE
Difficulty creating client from YelpEx.Client.Base

### ISSUE THREAD

**Issue by bmfay** [jdesilvio/yelp_ex#7]
I am trying to create my own client from YelpEx.Client.Base per the instructions in the documentation.  Quite simple:

```
defmodule MyApi.Yelp do
  use YelpEx.Client.Base

  def get_business_details(yelp_id, options) do
    get("businesses/#{yelp_id}", [], options)
  end

  def get_business_reviews(yelp_id, options) do
    get("businesses/#{yelp_id}/reviews", [], options)
  end
end
```

However when I try to call 

```
MyApi.Yelp.get_business_details(yelp_id, [])
```

I get the following error:

** (exit) exited in: GenServer.call(MyApi.Yelp, {:get, "businesses/Qt1x-Yvc6U0xxJlnA2-2uw", "", [], []}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started

I do not suspect this is necessarily due to anything wrong with YelpEx, but thought you might be able to point me towards what I'm missing.  Thank you!

**Comment by jdesilvio** [comment]
Hi, are you adding `yelp_ex` to your `applications/extra_applications`? See [here](https://github.com/jdesilvio/yelp_ex#installation).

**Comment by jdesilvio** [comment]
Does your main module look something like [this](https://github.com/jdesilvio/yelp_ex/blob/master/lib/yelp_ex.ex)?

**Comment by bmfay** [comment]
Thanks for the quick response @jdesilvio !  My issue was indeed that I was not adding my custom client as a worker started by the supervisor.  Thanks for your help!
